# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/carlosroman/stack-terminator
    environment:
      - DEP_VERSION=0.4.1
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
      - run: chmod +x $GOPATH/bin/dep
      - run: make deps test
